### ISSUE TITLE
filtering removes EventHandlers

### ISSUE THREAD

**Issue by charlestmichael** [predixdesignsystem/px-data-table#141]
## Expected behavior and actual behavior:
Expected behavior: Text boxes in the px-data-table that have event handlers attached to them should retain those event handlers during and after filtering.
Actual behavior: The event handlers are being removed from the text boxes
## Steps to reproduce the problem:
1. I created a px-data-table and added a column of type 'html' that contained a textbox. The reason that I did not use the standard editable column of type string is that some cells in the column require text input while others require a drop-down
2. I attached eventHandlers to the textboxes by querying the dom for each textbox and attaching a 'keyup' event handler by which I could validate the user input against a pattern (regex) defined in the html of the text box every time a key was pressed, thereby immediately notifying the user of invalid data input.
3. I made other columns in the table filterable, but not the 'html' column.
4. I filtered some of the other columns in the data table.
5. While the table was filtered, the eventHandlers no longer existed.
6. When I unfiltered the other fields, the eventHandlers did not return.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_)
px-data-table version 3.0.2
chrome version 58.0.3029.110 (64-bit)
OS: Windows Server 2012 R2 Standard
Hardware HP Z440

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        
Creating the handlers:

![image](https://user-images.githubusercontent.com/11964020/27136666-e6149088-50e9-11e7-8e45-7e67edb8d591.png)

The editing code
![image](https://user-images.githubusercontent.com/11964020/27136883-668dd9d6-50ea-11e7-8e98-8195dca37aad.png)

Table definition
![image](https://user-images.githubusercontent.com/11964020/27136743-0e90682a-50ea-11e7-8567-78802541ef00.png)

**Comment by randyaskin** [comment]
When the data-table is filtered and sorted, the DOM elements are actually destroyed and recreated - otherwise we wouldn't be able to filter across multiple pages without actually maintaining and showing/hiding all (potentially thousands) of those rows. I don't believe there's any way we could achieve the ability to attach persistent event handlers without completely re-architecting the way the data-table is built.

Conversely, I'm also not sure how we could support a single column with different types of cells and different validation logic without significantly increasing the complexity of the tableData property. Have you seen any examples of this in other table solutions? Maybe a rendering function would achieve this?

**Comment by mdwragg** [comment]
Closing due to age and release of https://www.predix-ui.com/#/elements/data-grid/px-data-grid
